name: protoSpaceJAM-portal
channels:
  - anaconda
  - defaults
dependencies:
  - biopython=1.78
  - numpy=1.21.2
  - openpyxl=3.0.5
  - pandas=1.1.3
  - python=3.8.5
  - requests=2.28.1
  - pip=20.2.4
  - pip:
    - django==4.1.2
    - djangorestframework==3.14.0
    - primer3-py==0.6.1
